name: Deploy pipeline for new release

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'

  workflow_dispatch:

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: install build
        run: python -m pip install build --user

      - name: build wheel and source tarball
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYTHON_CVPOM_PYPI_ACCESS_TOKEN }}