name: CV_POM CI unit tests workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v4
      - name: setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: install requirements
        run: python -m pip install -r requirements.txt
      - name: Analysing the code with ruff
        uses: chartboost/ruff-action@v1
      - name: Unit tests
        run: python -m pytest test -s -p no:warnings
